// Generated by the protocol buffer compiler.  DO NOT EDIT!

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "idiom/history.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace idiom {

namespace {

const ::google::protobuf::Descriptor* HistoryProto_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  HistoryProto_reflection_ = NULL;
const ::google::protobuf::Descriptor* HistoryTableProto_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  HistoryTableProto_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_idiom_2fhistory_2eproto() {
  protobuf_AddDesc_idiom_2fhistory_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "idiom/history.proto");
  GOOGLE_CHECK(file != NULL);
  HistoryProto_descriptor_ = file->message_type(0);
  static const int HistoryProto_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(HistoryProto, iroot_id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(HistoryProto, seed_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(HistoryProto, success_),
  };
  HistoryProto_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      HistoryProto_descriptor_,
      HistoryProto::default_instance_,
      HistoryProto_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(HistoryProto, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(HistoryProto, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(HistoryProto));
  HistoryTableProto_descriptor_ = file->message_type(1);
  static const int HistoryTableProto_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(HistoryTableProto, history_),
  };
  HistoryTableProto_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      HistoryTableProto_descriptor_,
      HistoryTableProto::default_instance_,
      HistoryTableProto_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(HistoryTableProto, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(HistoryTableProto, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(HistoryTableProto));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_idiom_2fhistory_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    HistoryProto_descriptor_, &HistoryProto::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    HistoryTableProto_descriptor_, &HistoryTableProto::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_idiom_2fhistory_2eproto() {
  delete HistoryProto::default_instance_;
  delete HistoryProto_reflection_;
  delete HistoryTableProto::default_instance_;
  delete HistoryTableProto_reflection_;
}

void protobuf_AddDesc_idiom_2fhistory_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\023idiom/history.proto\022\005idiom\"\?\n\014HistoryP"
    "roto\022\020\n\010iroot_id\030\001 \002(\r\022\014\n\004seed\030\002 \002(\r\022\017\n\007"
    "success\030\003 \001(\010\"9\n\021HistoryTableProto\022$\n\007hi"
    "story\030\001 \003(\0132\023.idiom.HistoryProto", 152);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "idiom/history.proto", &protobuf_RegisterTypes);
  HistoryProto::default_instance_ = new HistoryProto();
  HistoryTableProto::default_instance_ = new HistoryTableProto();
  HistoryProto::default_instance_->InitAsDefaultInstance();
  HistoryTableProto::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_idiom_2fhistory_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_idiom_2fhistory_2eproto {
  StaticDescriptorInitializer_idiom_2fhistory_2eproto() {
    protobuf_AddDesc_idiom_2fhistory_2eproto();
  }
} static_descriptor_initializer_idiom_2fhistory_2eproto_;


// ===================================================================

#ifndef _MSC_VER
const int HistoryProto::kIrootIdFieldNumber;
const int HistoryProto::kSeedFieldNumber;
const int HistoryProto::kSuccessFieldNumber;
#endif  // !_MSC_VER

HistoryProto::HistoryProto()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void HistoryProto::InitAsDefaultInstance() {
}

HistoryProto::HistoryProto(const HistoryProto& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void HistoryProto::SharedCtor() {
  _cached_size_ = 0;
  iroot_id_ = 0u;
  seed_ = 0u;
  success_ = false;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

HistoryProto::~HistoryProto() {
  SharedDtor();
}

void HistoryProto::SharedDtor() {
  if (this != default_instance_) {
  }
}

void HistoryProto::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* HistoryProto::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return HistoryProto_descriptor_;
}

const HistoryProto& HistoryProto::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_idiom_2fhistory_2eproto();  return *default_instance_;
}

HistoryProto* HistoryProto::default_instance_ = NULL;

HistoryProto* HistoryProto::New() const {
  return new HistoryProto;
}

void HistoryProto::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    iroot_id_ = 0u;
    seed_ = 0u;
    success_ = false;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool HistoryProto::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required uint32 iroot_id = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &iroot_id_)));
          set_has_iroot_id();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_seed;
        break;
      }
      
      // required uint32 seed = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_seed:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &seed_)));
          set_has_seed();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(24)) goto parse_success;
        break;
      }
      
      // optional bool success = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_success:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &success_)));
          set_has_success();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }
      
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void HistoryProto::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required uint32 iroot_id = 1;
  if (has_iroot_id()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->iroot_id(), output);
  }
  
  // required uint32 seed = 2;
  if (has_seed()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(2, this->seed(), output);
  }
  
  // optional bool success = 3;
  if (has_success()) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(3, this->success(), output);
  }
  
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* HistoryProto::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required uint32 iroot_id = 1;
  if (has_iroot_id()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->iroot_id(), target);
  }
  
  // required uint32 seed = 2;
  if (has_seed()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(2, this->seed(), target);
  }
  
  // optional bool success = 3;
  if (has_success()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(3, this->success(), target);
  }
  
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int HistoryProto::ByteSize() const {
  int total_size = 0;
  
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required uint32 iroot_id = 1;
    if (has_iroot_id()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->iroot_id());
    }
    
    // required uint32 seed = 2;
    if (has_seed()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->seed());
    }
    
    // optional bool success = 3;
    if (has_success()) {
      total_size += 1 + 1;
    }
    
  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void HistoryProto::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const HistoryProto* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const HistoryProto*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void HistoryProto::MergeFrom(const HistoryProto& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_iroot_id()) {
      set_iroot_id(from.iroot_id());
    }
    if (from.has_seed()) {
      set_seed(from.seed());
    }
    if (from.has_success()) {
      set_success(from.success());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void HistoryProto::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void HistoryProto::CopyFrom(const HistoryProto& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool HistoryProto::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000003) != 0x00000003) return false;
  
  return true;
}

void HistoryProto::Swap(HistoryProto* other) {
  if (other != this) {
    std::swap(iroot_id_, other->iroot_id_);
    std::swap(seed_, other->seed_);
    std::swap(success_, other->success_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata HistoryProto::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = HistoryProto_descriptor_;
  metadata.reflection = HistoryProto_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int HistoryTableProto::kHistoryFieldNumber;
#endif  // !_MSC_VER

HistoryTableProto::HistoryTableProto()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void HistoryTableProto::InitAsDefaultInstance() {
}

HistoryTableProto::HistoryTableProto(const HistoryTableProto& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void HistoryTableProto::SharedCtor() {
  _cached_size_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

HistoryTableProto::~HistoryTableProto() {
  SharedDtor();
}

void HistoryTableProto::SharedDtor() {
  if (this != default_instance_) {
  }
}

void HistoryTableProto::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* HistoryTableProto::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return HistoryTableProto_descriptor_;
}

const HistoryTableProto& HistoryTableProto::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_idiom_2fhistory_2eproto();  return *default_instance_;
}

HistoryTableProto* HistoryTableProto::default_instance_ = NULL;

HistoryTableProto* HistoryTableProto::New() const {
  return new HistoryTableProto;
}

void HistoryTableProto::Clear() {
  history_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool HistoryTableProto::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .idiom.HistoryProto history = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_history:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_history()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(10)) goto parse_history;
        if (input->ExpectAtEnd()) return true;
        break;
      }
      
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void HistoryTableProto::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // repeated .idiom.HistoryProto history = 1;
  for (int i = 0; i < this->history_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->history(i), output);
  }
  
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* HistoryTableProto::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // repeated .idiom.HistoryProto history = 1;
  for (int i = 0; i < this->history_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        1, this->history(i), target);
  }
  
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int HistoryTableProto::ByteSize() const {
  int total_size = 0;
  
  // repeated .idiom.HistoryProto history = 1;
  total_size += 1 * this->history_size();
  for (int i = 0; i < this->history_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->history(i));
  }
  
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void HistoryTableProto::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const HistoryTableProto* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const HistoryTableProto*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void HistoryTableProto::MergeFrom(const HistoryTableProto& from) {
  GOOGLE_CHECK_NE(&from, this);
  history_.MergeFrom(from.history_);
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void HistoryTableProto::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void HistoryTableProto::CopyFrom(const HistoryTableProto& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool HistoryTableProto::IsInitialized() const {
  
  for (int i = 0; i < history_size(); i++) {
    if (!this->history(i).IsInitialized()) return false;
  }
  return true;
}

void HistoryTableProto::Swap(HistoryTableProto* other) {
  if (other != this) {
    history_.Swap(&other->history_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata HistoryTableProto::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = HistoryTableProto_descriptor_;
  metadata.reflection = HistoryTableProto_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace idiom

// @@protoc_insertion_point(global_scope)
